---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: activiti-cloud-sso-idm-kub
spec:
  replicas: 1
  template:
    metadata:
      name: activiti-cloud-sso-idm-kub
      labels:
        app: infrastructure
        serviceType: sso-idm
    spec:
      containers:
      - name: activiti-cloud-sso-idm-kub
        image: activiti/activiti-cloud-sso-idm:7-201801-EA
        imagePullPolicy: Always
        ports:
        - containerPort: 30081
        env:
#        - name: JAVA_OPTS
#          value: -Xmx256m -Xms256m
        - name: PORT_OFFSET
          value: "22001"
        - name: DB_VENDOR
          value: "H2"
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-cloud-sso-idm-kub
  namespace: default
spec:
  selector:
    serviceType: sso-idm
  ports:
    - port: 30081
      targetPort: 30081
#      nodePort: 30081 # uncomment for minikube, comment for Kube
  type: LoadBalancer #NodePort for minikube, LoadBalancer for Kube
---
