apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: modeling-app
  labels:
    app: infrastructure
    serviceType: modeling
spec:
  replicas: 1
  template:
    metadata:
      name: modeling-app
      labels:
        app: infrastructure
        serviceType: modeling
    spec:
      containers:
        - name: modeling-app
          image: activiti/activiti-cloud-modeling-backend:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 100
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 15
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
          - name: JAVA_OPTS
            value: -Xmx128m -Xms128m
          - name: SPRING_PROFILES_ACTIVE
            value: kube,local
          - name: ACT_CLOUD_CONFIG_SERVER_ENABLED
            value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: modeling-app
  namespace: default
spec:
  selector:
    serviceType: modeling
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP
---
