version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  activiti-cloud-sso-idm:
    image: activiti/activiti-cloud-sso-idm:latest
    ports:
      - "8180:8180"
  activiti-cloud-audit:
    image: activiti/activiti-cloud-audit:latest
    restart: always
    links:
      - activiti-cloud-sso-idm:activiti-cloud-sso-idm
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
    depends_on:
      activiti-cloud-config-server:
         condition: service_healthy
    environment:
      - ACT_AUDIT_PORT=8181
      - ACT_CLOUD_CONFIG_FAIL_FAST=true
  activiti-cloud-query:
    image: activiti/activiti-cloud-query:latest
    restart: always
    links:
      - activiti-cloud-sso-idm:activiti-cloud-sso-idm
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
    depends_on:
      activiti-cloud-config-server:
         condition: service_healthy
    environment:
      - ACT_QUERY_PORT=8182
      - ACT_CLOUD_CONFIG_FAIL_FAST=true
  activiti-cloud-registry:
    image: activiti/activiti-cloud-registry:latest
    restart: always
    ports:
     - "8761:8761"
  activiti-cloud-gateway:
    image: activiti/activiti-cloud-gateway:latest
    restart: always
    links:
     - activiti-cloud-registry
    depends_on:
       activiti-cloud-config-server:
            condition: service_healthy
    environment:
      - ACT_CLOUD_CONFIG_FAIL_FAST=true
    ports:
      - "8080:8080"
  activiti-cloud-config-server:
    image: activiti/activiti-cloud-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/ryandawsonuk/activiti-cloud-config-repo